# Generated by Django 5.1.1 on 2024-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_shubham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shubham',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
