# Generated by Django 5.1.1 on 2024-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_shubham_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shubham',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
